apiVersion: apps/v1
kind: Deployment
metadata:
  name: hh-bot
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hh-bot
      env: staging
  template:
    metadata:
      labels:
        app: hh-bot
        env: staging
      namespace: default
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - env:
          - name: ENV
            value: dev
          - name: CLIENT_ID
            value: 'KTJU0OMC88I9HP6E85PL44Q10PAC73I5DOIR5HMT4ME45DKOGJPSKP2F3VRUVM34'
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: hh-bot-secrets-dev
                key: BOT_TOKEN
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: hh-bot-secrets-dev
                key: MONGODB_URL
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: hh-bot-secrets-dev
                key: CLIENT_SECRET
          - name: REDIRECT_URI
            value: 'https://dev.hhbot.pterko.ru/hh_redirect_uri'
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: hh-bot-secrets-dev
                key: RABBITMQ_URL
          image: registry.gitlab.com/pter/hh-ru-telegram-bot/bot:dev
          imagePullPolicy: Always
          name: hh-bot
          ports:
          - containerPort: 12000
            name: setnamehere
            protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0