apiVersion: apps/v1
kind: Deployment
metadata:
  name: hh-bot-views-updater
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hh-bot-views-updater
      env: staging
  template:
    metadata:
      labels:
        app: hh-bot-views-updater
        env: staging
      namespace: default
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: ENV
          value: dev
        - name: CLIENT_ID
          value: '123'
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: hh-bot-secrets-dev
              key: BOT_TOKEN
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: hh-bot-secrets-dev
              key: MONGODB_URL
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: hh-bot-secrets-dev
              key: CLIENT_SECRET
        - name: REDIRECT_URI
          value: 'https://dev.hhbot.pterko.ru/hh_redirect_uri'
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: hh-bot-secrets-dev
              key: RABBITMQ_URL
        image: registry.gitlab.com/pter/hh-ru-telegram-bot/views-updater:dev
        imagePullPolicy: Always
        name: hh-bot-views-updater
        ports:
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0