apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hh-bot-letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: pter96@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: hh-bot-letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
