stages:
  - build 
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    - docker build --tag $CI_REGISTRY_IMAGE/bot:$CI_COMMIT_REF_SLUG -f Dockerfile.bot .
    - docker push $CI_REGISTRY_IMAGE/bot:$CI_COMMIT_REF_SLUG

    - docker build --tag $CI_REGISTRY_IMAGE/resume-updater:$CI_COMMIT_REF_SLUG -f Dockerfile.resume-updater .
    - docker push $CI_REGISTRY_IMAGE/resume-updater:$CI_COMMIT_REF_SLUG

    - docker build --tag $CI_REGISTRY_IMAGE/token-updater:$CI_COMMIT_REF_SLUG -f Dockerfile.token-updater .
    - docker push $CI_REGISTRY_IMAGE/token-updater:$CI_COMMIT_REF_SLUG

    - docker build --tag $CI_REGISTRY_IMAGE/views-updater:$CI_COMMIT_REF_SLUG -f Dockerfile.views-updater .
    - docker push $CI_REGISTRY_IMAGE/views-updater:$CI_COMMIT_REF_SLUG
  only:
    - master
    - dev

deploy_dev:
  stage: deploy
  image: 
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - export SERVICE_DOMAIN=dev.hhbot.pterko.ru



    - kubectl version
    - apk add --no-cache gettext

    - kubectl delete -n $KUBE_NAMESPACE secret regcred || true
    - kubectl create secret -n $KUBE_NAMESPACE docker-registry regcred --docker-server=registry.gitlab.com --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD

    - cd devops
    - envsubst < bot.yml > bot2.yml
    - envsubst < resume-updater.yml > resume-updater2.yml
    - envsubst < token-updater.yml > token-updater2.yml
    - envsubst < views-updater.yml > views-updater2.yml



    - kubectl apply -f issuer.yml || true
    

    - |
      kubectl apply -f bot2.yml
      kubectl patch deployment hh-bot -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status deployment/hh-bot
    #   kubectl rollout status -f bot2.yml
    #   kubectl patch -f bot2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"

    - |
      kubectl apply -f resume-updater2.yml 
      kubectl patch -f resume-updater2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status -f resume-updater2.yml

    - |
      kubectl apply -f token-updater2.yml 
      kubectl patch -f token-updater2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status -f token-updater2.yml

    - |
      kubectl apply -f views-updater2.yml 
      kubectl patch -f views-updater2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status -f views-updater2.yml
    
    - kubectl get all
  environment:
    name: dev
    url: https://dev.hhbot.pterko.ru
  only:
    - dev


        
deploy_prod:
  stage: deploy
  image: 
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - export SERVICE_DOMAIN=master.hhbot.pterko.ru




    - kubectl version
    - apk add --no-cache gettext

    - kubectl delete -n $KUBE_NAMESPACE secret regcred || true
    - kubectl create secret -n $KUBE_NAMESPACE docker-registry regcred --docker-server=registry.gitlab.com --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD

    - cd devops
    - envsubst < bot.yml > bot2.yml
    - envsubst < resume-updater.yml > resume-updater2.yml
    - envsubst < token-updater.yml > token-updater2.yml
    - envsubst < views-updater.yml > views-updater2.yml



    - kubectl apply -f issuer.yml || true
    

    - |
      kubectl apply -f bot2.yml
      kubectl patch deployment hh-bot -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status deployment/hh-bot
    #   kubectl rollout status -f bot2.yml
    #   kubectl patch -f bot2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"

    - |
      kubectl apply -f resume-updater2.yml 
      kubectl patch -f resume-updater2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status -f resume-updater2.yml

    - |
      kubectl apply -f token-updater2.yml 
      kubectl patch -f token-updater2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status -f token-updater2.yml

    - |
      kubectl apply -f views-updater2.yml 
      kubectl patch -f views-updater2.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      kubectl rollout status -f views-updater2.yml
    
    - kubectl get all
  environment:
    name: master
    url: https://master.hhbot.pterko.ru
  only:
    - master